version: "3.8"

services:
  openresty:
    container_name: mycontainer
    build:
      context: .
      args:
      - RESTY_RPM_FLAVOR="-debug"
    environment:
      - NGINX_ENV=${NGINX_ENV}
    ports:
    - '${PORT}:80'
